### ISSUE TITLE
Doesn't compile on ubuntu 12.04 32bit

### ISSUE THREAD

**Issue by adrianrly** [ashleynewson/SmartSim#1]
./configure went well but it doesn't compile on ubuntu 12.04 32bit

/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:106: undefined reference to `g_return_if_fail_warning'
smartsim-propertyitem-propertyset.o: In function`property_set_index_of_item':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:167: undefined reference to `g_strcmp0'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:130: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:129: undefined reference to `g_return_if_fail_warning'
smartsim-propertyitem-propertyset.o: In function`property_set_get_item':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:224: undefined reference to `g_strcmp0'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:186: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:187: undefined reference to `g_return_if_fail_warning'
smartsim-propertyitem-propertyset.o: In function`_vala_array_dup91':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:249: undefined reference to `g_malloc0_n'
smartsim-propertyitem-propertyset.o: In function`_vala_array_add104':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:262: undefined reference to `g_realloc_n'
smartsim-propertyitem-propertyset.o: In function`_vala_array_dup92':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:272: undefined reference to `g_malloc0_n'
smartsim-propertyitem-propertyset.o: In function`property_set_add_item':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:302: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:303: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-propertyset.o: In function `property_set_get_type':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:362: undefined reference to`g_once_init_enter'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:365: undefined reference to `g_type_register_static'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:366: undefined reference to`g_once_init_leave'
smartsim-propertyitem-propertyset.o: In function `property_set_finalize':
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:348: undefined reference to`g_type_check_instance_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-propertyset.c:350: undefined reference to `g_type_check_class_cast'
smartsim-propertyitem-selection.o: In function`property_item_selection_class_init':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:870: undefined reference to `g_type_class_peek_parent'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:871: undefined reference to`g_type_check_class_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:872: undefined reference to `g_type_class_add_private'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:873: undefined reference to`g_type_check_class_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:874: undefined reference to `g_type_check_class_cast'
smartsim-propertyitem-selection.o: In function`_vala_array_free':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:917: undefined reference to `g_free'
smartsim-propertyitem-selection.o: In function`property_item_selection_real_create_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:630: undefined reference to `gtk_vbox_new'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:631: undefined reference to`g_object_ref_sink'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:633: undefined reference to `g_malloc0'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:679: undefined reference to`gtk_radio_button_new_with_label'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:680: undefined reference to `g_object_ref_sink'
smartsim-propertyitem-selection.o: In function`_g_object_ref0':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:598: undefined reference to `g_object_ref'
smartsim-propertyitem-selection.o: In function`property_item_selection_real_create_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:712: undefined reference to `gtk_box_pack_start'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:713: undefined reference to`g_object_unref'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:700: undefined reference to `gtk_radio_button_new_with_label_from_widget'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:701: undefined reference to`g_object_ref_sink'
smartsim-propertyitem-selection.o: In function `_vala_array_add106':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:605: undefined reference to`g_realloc_n'
smartsim-propertyitem-selection.o: In function `property_item_selection_real_create_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:729: undefined reference to`gtk_toggle_button_set_active'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:732: undefined reference to `g_object_unref'
smartsim-propertyitem-selection.o: In function`property_item_selection_set_selected':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:847: undefined reference to `g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function`property_item_selection_real_read_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:746: undefined reference to `gtk_vbox_get_type'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:746: undefined reference to`g_type_check_instance_is_a'
smartsim-propertyitem-selection.o: In function `_g_object_ref0':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:598: undefined reference to`g_object_ref'
smartsim-propertyitem-selection.o: In function `property_item_selection_real_read_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:761: undefined reference to`gtk_container_get_children'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:764: undefined reference to `g_list_length'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:826: undefined reference to`g_list_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:741: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:821: undefined reference to`g_object_unref'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:800: undefined reference to `g_list_nth_data'
smartsim-propertyitem-selection.o: In function`_g_object_ref0':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:598: undefined reference to `g_object_ref'
smartsim-propertyitem-selection.o: In function`property_item_selection_real_read_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:804: undefined reference to `gtk_radio_button_get_type'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:804: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:809: undefined reference to `g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:809: undefined reference to`gtk_toggle_button_get_active'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:815: undefined reference to `g_object_unref'
smartsim-propertyitem-selection.o: In function`property_item_string_error_quark':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:138: undefined reference to `g_quark_from_static_string'
smartsim-propertyitem-selection.o: In function`property_item_selection_construct':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:423: undefined reference to `g_malloc0'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:424: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:418: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:419: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function `_vala_array_dup93':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:440: undefined reference to`g_malloc0_n'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:443: undefined reference to `g_strdup'
smartsim-propertyitem-selection.o: In function`property_item_selection_add_option':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:501: undefined reference to `g_strdup'
smartsim-propertyitem-selection.o: In function`_vala_array_add105':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:453: undefined reference to `g_realloc_n'
smartsim-propertyitem-selection.o: In function`_vala_array_dup94':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:463: undefined reference to `g_malloc0_n'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:466: undefined reference to`g_strdup'
smartsim-propertyitem-selection.o: In function `property_item_selection_add_option':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:507: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:510: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:501: undefined reference to`g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:490: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:489: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function `property_item_selection_get_option':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:524: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function `property_item_selection_set_option':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:582: undefined reference to`g_strcmp0'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:547: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:546: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function `property_item_selection_get_type':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:893: undefined reference to`g_once_init_enter'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:896: undefined reference to `g_type_register_static'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:897: undefined reference to`g_once_init_leave'
smartsim-propertyitem-selection.o: In function `property_item_selection_instance_init':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:879: undefined reference to`g_type_instance_get_private'
smartsim-propertyitem-selection.o: In function `property_item_selection_finalize':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:885: undefined reference to`g_type_check_instance_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:886: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:887: undefined reference to`g_type_check_class_cast'
smartsim-propertyitem-selection.o: In function `property_item_selection_set_data_throw':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:246: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:314: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:316: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:319: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:321: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:323: undefined reference to `g_error_new_literal'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:325: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:326: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:327: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:328: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:336: undefined reference to`g_quark_to_string'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:336: undefined reference to `g_log'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:337: undefined reference to`g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:331: undefined reference to `g_propagate_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:235: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:236: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:237: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:274: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:276: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:279: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:281: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:284: undefined reference to `g_strconcat'
smartsim-propertyitem-selection.o:/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:286: more undefined references to`g_strconcat' follow
smartsim-propertyitem-selection.o: In function `property_item_selection_set_data_throw':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:288: undefined reference to`g_error_new_literal'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:290: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:291: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:292: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:293: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:294: undefined reference to `g_free'
smartsim-propertyitem-selection.o:/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:295: more undefined references to`g_free' follow
smartsim-propertyitem-selection.o: In function `property_item_selection_set_data_throw':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:303: undefined reference to`g_quark_to_string'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:298: undefined reference to `g_propagate_error'
smartsim-propertyitem-selection.o: In function`property_item_selection_set_data':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:401: undefined reference to `g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:383: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:384: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:385: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function `property_item_selection_get_data_throw':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:173: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:185: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:187: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:190: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:192: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:194: undefined reference to `g_error_new_literal'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:196: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:197: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:198: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:199: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:202: undefined reference to`g_propagate_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:207: undefined reference to `g_quark_to_string'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:207: undefined reference to`g_log'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:208: undefined reference to `g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:163: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:164: undefined reference to `g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function`property_item_selection_get_data':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:368: undefined reference to `g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:370: undefined reference to`g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:347: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:348: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-selection.o: In function `property_item_selection_real_read_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:827: undefined reference to`g_object_unref'
smartsim-propertyitem-selection.o: In function `property_item_selection_get_option':
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:538: undefined reference to`g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-selection.c:529: undefined reference to `g_strdup'
smartsim-propertyitem-string.o: In function`property_item_string_class_init':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:404: undefined reference to `g_type_class_peek_parent'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:405: undefined reference to`g_type_check_class_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:406: undefined reference to `g_type_check_class_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:407: undefined reference to`g_type_check_class_cast'
smartsim-propertyitem-string.o: In function `property_item_string_real_create_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:367: undefined reference to`gtk_entry_new'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:368: undefined reference to `g_object_ref_sink'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:371: undefined reference to`gtk_entry_set_text'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:372: undefined reference to `g_object_set'
smartsim-propertyitem-string.o: In function`property_item_string_real_read_widget':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:387: undefined reference to `gtk_entry_get_type'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:387: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:393: undefined reference to `gtk_entry_get_text'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:395: undefined reference to`g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:396: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:382: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-string.o: In function `property_item_string_construct':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:347: undefined reference to`g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:348: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:340: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:341: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:342: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-string.o: In function `property_item_string_get_type':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:425: undefined reference to`g_once_init_enter'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:428: undefined reference to `g_type_register_static'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:429: undefined reference to`g_once_init_leave'
smartsim-propertyitem-string.o: In function `property_item_string_finalize':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:417: undefined reference to`g_type_check_instance_cast'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:418: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:419: undefined reference to`g_type_check_class_cast'
smartsim-propertyitem-string.o: In function `property_item_string_set_data_throw':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:220: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:235: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:237: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:240: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:242: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:244: undefined reference to `g_error_new_literal'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:246: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:247: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:248: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:249: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:257: undefined reference to`g_quark_to_string'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:257: undefined reference to `g_log'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:258: undefined reference to`g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:226: undefined reference to `g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:227: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:227: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:227: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:228: undefined reference to `g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:209: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:211: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:210: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:252: undefined reference to `g_propagate_error'
smartsim-propertyitem-string.o: In function`property_item_string_set_data':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:322: undefined reference to `g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:304: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:305: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:306: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-string.o: In function `property_item_string_get_data_throw':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:145: undefined reference to`g_type_check_instance_is_a'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:159: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:161: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:164: undefined reference to `g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:166: undefined reference to`g_strconcat'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:168: undefined reference to `g_error_new_literal'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:170: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:171: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:172: undefined reference to`g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:173: undefined reference to `g_free'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:176: undefined reference to`g_propagate_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:151: undefined reference to `g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:181: undefined reference to`g_quark_to_string'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:181: undefined reference to `g_log'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:182: undefined reference to`g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:135: undefined reference to `g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:136: undefined reference to`g_return_if_fail_warning'
smartsim-propertyitem-string.o: In function `property_item_string_get_data':
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:289: undefined reference to`g_clear_error'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:291: undefined reference to `g_strdup'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:268: undefined reference to`g_return_if_fail_warning'
/tmp/SmartSim/ccode/propertyitem/propertyitem-string.c:269: undefined reference to `g_return_if_fail_warning'
collect2: ld returned 1 exit status
make[2]: *** [smartsim] Error 1
make[2]: Leaving directory`/tmp/SmartSim/ccode'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/tmp/SmartSim'
make: **\* [all] Error 2
adrian@Adrian-Lnx:/tmp/SmartSim$
